.PHONY: install

install:
	cp -R .vim ~
	cp .Xmodmap ~
	cp .Xresources ~
	cp .Xresources_solarized_dark ~
	cp .Xresources_solarized_light ~
	cp .bash_profile ~
	cp .bashrc ~
	cp .conkyrc ~
	cp .cwmrc ~
	cp .dircolors ~
	cp .gvimrc ~
	cp .kshrc ~
	cp .nexrc ~
	cp .profile ~
	cp .synclient ~
	cp .tmux.conf ~
	cp .vimrc ~
	cp .xinitrc ~
	cp .xsession ~
