#!/bin/sh

# Open file(s) in the appropriate program.

function op_file() {
    type="$1"
    path="$2"

    case "$type" in
    pdf|ps)
        evince "$path" > /dev/null 2>&1 &
        disown
        ;;
    chm)
        xchm "$path" > /dev/null 2>&1 &
        disown
        ;;
    html|htm)
        firefox "$path" > /dev/null 2>&1 &
        disown
        ;;
    odt)
        ooffice "$path" > /dev/null 2>&1 &
        disown
        ;;
    *)
        echo "$path: don't know how to open a $type file" 1>&2
        return 1
        ;;
    esac
}

while [ $# -gt 0 ]; do
    path="$1"
    type=`echo "${1##*.}" | tr '[A-Z]' '[a-z]'`
    op_file "$type" "$path"
    shift
done

