#!/bin/sh

# Open file(s) in the appropriate program.

case $SHELL in
*bash)
    disown_cmd=disown
    ;;
*)
    disown_cmd=:
    ;;
esac

op_file() {
    type=$(echo "$1" | tr '[:upper:]' '[:lower:]')
    path="$2"

    case "$type" in
    pdf|ps|djvu)
        for prog in evince mupdf; do
            if which "$prog" > /dev/null 2>&1; then
                $prog "$path" > /dev/null 2>&1 &
                $disown_cmd
                break
            fi
        done
        ;;
    chm)
        xchm "$path" > /dev/null 2>&1 &
        $disown_cmd
        ;;
    html|htm)
        firefox "$path" > /dev/null 2>&1 &
        $disown_cmd
        ;;
    odt|doc|xls|docx)
        ooffice "$path" > /dev/null 2>&1 &
        $disown_cmd
        ;;
    *)
        echo "$path: don't know how to open a $type file" 1>&2
        return 1
        ;;
    esac
}

while [ $# -gt 0 ]; do
    path="$1"
    type=`echo "${1##*.}" | tr '[A-Z]' '[a-z]'`
    op_file "$type" "$path"
    shift
done

