all: findsrc grepsrc

install: findsrc grepsrc
	mkdir -p ~/bin
	cp -f findsrc grepsrc ~/bin
	ln -fs ~/bin/findsrc ~/bin/findmak
	ln -fs ~/bin/grepsrc ~/bin/grepisrc
	ln -fs ~/bin/grepsrc ~/bin/grepsym
	ln -fs ~/bin/grepsrc ~/bin/grepisym
