#!/bin/sh

# grepsrc
# grepsym
# grepisrc
# grepsym

# grep source code files.
# Modifiers:
#  *i* -- ignore case.
#  *sym -- search for a whole word.

if [ $# -eq 0 ]; then
    echo "usage: $0 <needle> [<dir1> <dir2>...]" 2>&1
    exit 1
fi

progname=${0##*/}

case "$progname" in
grepi*)
    greopopts="${grepopts} -i"
    ;;
esac

case "$progname" in
*sym)
    grepopts="${grepopts} -w"
    ;;
esac

case "$progname" in
grep*mak)
    findcmd=findmak
    ;;
*)
    findcmd=findsrc
    ;;
esac

needle="$1"

shift

$findcmd "$@" | sort | xargs grep -E -n $grepopts "$needle" /dev/null | color green "$needle"
