#!/bin/sh

# grepsrc
# grepsym
# grepisrc
# grepsym

# grep source code files.
# Modifiers:
#  *i* -- ignore case.
#  *sym -- search for a whole word.

if [ $# -eq 0 ]; then
    echo "usage: $0 <needle> [<dir1> <dir2>...]" 2>&1
    exit 1
fi

progname=${0##*/}

case "$progname" in
grepi*)
    ignorecase="-i"
    ;;
*)
    ignorecase=""
    ;;
esac

case "$progname" in
*sym)
    needle="\<${1}\>"
    ;;
*)
    needle="$1"
    ;;
esac

case "$progname" in
grep*mak)
    findcmd=findmak
    ;;
*)
    findcmd=findsrc
    ;;
esac

shift

$findcmd "$@" | sort | xargs egrep --color=auto -n $ignorecase "${needle}" /dev/null
