#!/bin/sh

cscope_opts='-Rqbuk'

if [ $# -eq 0 ]; then
    set '.'
fi

rm -f tags
findsrc "$@" | sort | xargs ctags -a -f tags

args=''
for arg in "$@"; do
    args="$args '-s${arg}'"
done
eval cscope $cscope_opts "$args"
