#!/bin/sh

AUTONET=/usr/local/libexec/autonet
LOG=/var/log/autonet.log

isrunning() {
    pgrep autonet > /dev/null 2>&1
}

dostart() {
    if ! isrunning; then
        $AUTONET > $LOG 2>&1 &
    fi
}

dostop() {
    pkill autonet
}

docheck() {
    if isrunning; then
        echo 1
    else
        echo 0
    fi
}

case "$1" in
start)
    dostart
    ;;
stop)
    dostop
    ;;
restart)
    dostop
    dostart
    ;;
check)
    docheck
    ;;
esac
